name: Push

on:
  push:
    branches-ignore:
      - main

env:
  TZ: "Asia/Tokyo"
  BLOGSYNC_USERNAME: ${{ vars.BLOGSYNC_USERNAME }}
  BLOGSYNC_PASSWORD: ${{ secrets.BLOGSYNC_PASSWORD }}
  BLOGSYNC_DOMAIN: ${{ vars.BLOGSYNC_DOMAIN }}

jobs:
  push:
    name: push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
      - uses: actions/setup-go@v1
        with:
          go-version: 1.20
      - name: Add to PATH
        run: go env GOPATH >> $GITHUB_PATH
      # - uses: actions/cache@v3
      #   with:
      #     path: ~/go/bin/
      #     key: ${{ runner.os }}-go-bin
      - name: Install blogsync
        run: go install github.com/x-motemen/blogsync@latest
      - name: blogsync push
        run:  |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
            blogsync push $file
          done
      # - name: notify to slack
      #   uses: mm0202/action_slack-notify@main
      #   if: always()
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}