name: Push

on:
  push:
    branches-ignore:
      - main

env:
  TZ: "Asia/Tokyo"
  BLOGSYNC_DOMAIN: ${{ secrets.BLGOSYNC_DOMAIN }}

jobs:
  push:
    name: push
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-go@v1
      id: go
      with:
        go-version: 1.20

    - uses: actions/cache@v3
      with:
        path: ~/go/bin/
        key: ${{ runner.os }}-go-bin

    - id: go
      run: |
        echo "GOPATH=$(go env GOPATH)" >> "$GITHUB_OUTPUT"

    # - run: git fetch origin main

    - name: Setup blogsync
      run: go install github.com/x-motemen/blogsync@latest

    - run: echo ${{ steps.go.outputs.GOPATH}}

    - name: push
      env:
        PATH: ${{ steps.go.outputs.GOPATH }}:$PATH
      run: |
        git diff origin/main --name-only -- entry | xargs -t -n1 blogsync push

    # - name: notify to slack
    #   uses: mm0202/action_slack-notify@main
    #   if: always()
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}